version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - /app/node_modules
      - '.:/app'
    networks:
      - app-network
    depends_on:
      - redis
  redis:
    image: 'redis/redis-stack:latest'
    command: 'redis-server --requirepass ${REDIS_PW}'
    ports:
      - '${REDIS_PORT:-6380}:6379'
      - '8001:8001'
    volumes:
      - 'redis-srv:/data'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
networks:
  app-network:
    driver: bridge
volumes:
  redis-srv:
    driver: local